In [97]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
data = pd.read_csv('train.csv').values
X = data[:,1:]
y = data[:,0]


def getData(X, Y, folds, normalize):
    
    if(normalize==True): X = X/X.max()
    
    kf = KFold(n_splits=folds)
    kf.get_n_splits(X)
    
    print(kf)  
    train_data = []
    test_data = []

    for train_index, test_index in kf.split(X):
        print(train_index, test_index)
        X_train, X_test = X[train_index], X[test_index]
        Y_train, Y_test = Y[train_index], Y[test_index]
        train_data.append((X_train,Y_train))
        test_data.append((X_test, Y_test))
        
    return train_data, test_data

getData(X,y,5,False)
# mlp = MLPClassifier()
# print(cross_val_score(mlp, X, y, cv=5)) 


KFold(n_splits=5, random_state=None, shuffle=False)
[ 8400  8401  8402 ... 41997 41998 41999] [   0    1    2 ... 8397 8398 8399]
[    0     1     2 ... 41997 41998 41999] [ 8400  8401  8402 ... 16797 16798 16799]
[    0     1     2 ... 41997 41998 41999] [16800 16801 16802 ... 25197 25198 25199]
[    0     1     2 ... 41997 41998 41999] [25200 25201 25202 ... 33597 33598 33599]
[    0     1     2 ... 33597 33598 33599] [33600 33601 33602 ... 41997 41998 41999]


([(array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
   array([5, 0, 9, ..., 7, 6, 9], dtype=int64)),
  (array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
   array([1, 0, 1, ..., 7, 6, 9], dtype=int64)),
  (array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
   array([1, 0, 1, ..., 7, 6, 9], dtype=int64)),
  (array([[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0,

In [96]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
data = pd.read_csv('train.csv').values
X = data[:1000,1:]
y = data[:1000,0]
X = X/X.max()
mlp = MLPClassifier()
print(cross_val_score(mlp, X, y, cv=5)) 


[0.83333333 0.86206897 0.82914573 0.86868687 0.87755102]


E:\Programs\Anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [ ]:
for i in range(5):
    X_train, y_train = 
    print(X_train)

In [90]:
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_val_score
diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
lasso = linear_model.Lasso()
print(cross_val_score(lasso, X, y, cv=3)) 

[0.33150734 0.08022311 0.03531764]
